package email.app;

import java.util.Scanner;

public class EmailApp {

    public static void main(String[] args) {
        Email email_1 = new Email("Kamal","Ranasinghe","AxelLanka", "Sales");
        Email email_2 = new Email("Amal","Gunasekara","ABCompany");

        email_1.setMailboxCapacity(5000);
        email_1.setAlternateEmail("sansan@gmail.com");

        Scanner sc = new Scanner(System.in);
        System.out.println("Change The Autogenerated Password");
        System.out.print("Enter The Auto Generated Password: ");
        String oldPw = sc.next().trim();
        System.out.print("Enter The New Password: ");
        String newPw = sc.next().trim();
        try{
            email_1.setPassword(oldPw,newPw);
        } catch(Exception ex) {
            ex.printStackTrace();
        }

        email_1.showInfo();
        email_2.showInfo();

    }
}
